apiVersion: v1
kind: Service
metadata:
  name: nestjs-microservice-service
spec:
  selector:
    app: nestjs-microservices
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: NodePort